name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          styles: |
            Vale
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
